spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb2?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          format_sql: true
          show_sql: true
          hbm2ddl:
            auto: update
server:
  port: 8001


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
